[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_SUPABASE_URL = "https://dkrgcyosyzdotnphpryw.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcmdjeW9zeXpkb3RucGhwcnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDIwNTcsImV4cCI6MjA3MDk3ODA1N30.2Fykgv0LrL-MKzj98skEsnG9BOGr11p7nBMXmXc-r2A"

# Next.js specific configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# API routes redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Remove the problematic redirect that was sending everything to index.html
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 